AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SlackWorkflowCreateGithubIssue

Parameters:
  VerificationToken:
    Type: String
  SlackBotToken:
    Type: String
  SlackSigningSecret:
    Type: String
  GithubToken:
    Type: String
  GithubRepo:
    Type: String

Resources:
  SlackWorkflowCreateGithubIssue:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SlackWorkflowCreateGithubIssue
      CodeUri: ./
      Handler: main.handler
      Runtime: python3.9
      MemorySize: 2048
      Timeout: 60
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          verification_token: !Ref VerificationToken
          slack_bot_token: !Ref SlackBotToken
          slack_signing_secret: !Ref SlackSigningSecret
          github_token: !Ref GithubToken
          github_repo: !Ref GithubRepo
      Policies:
        LambdaInvokePolicy:
          FunctionName: SlackWorkflowCreateGithubIssue
